FROM maven:3.6.3-openjdk-11 AS maven_build
COPY pom.xml /build/
COPY src /build/src/
WORKDIR /build/
RUN mvn package
USER root
RUN chmod -R 777 /build

FROM openjdk
RUN mkdir -p /tmp/app
RUN groupadd -g 1010 javagroup
RUN useradd -u 1500 javauser
RUN usermod -a -G javagroup javauser
ENV SERVER_PORT=8080
ENV ARTIFACT_NAME spring-boot.jar
ARG JAR_FILE=/build/target/*.jar
chown -R 1010:javagroup /tmp
WORKDIR /tmp
USER 1010
COPY --chown=1010:javagroup --from=maven_build  /build/target/*.jar /tmp/spring-boot.jar
EXPOSE $SERVER_PORT
ENTRYPOINT ["java","-jar","/tmp/spring-boot.jar"] USER 1010