FROM maven:3.6.3-openjdk-11 AS maven_build
COPY pom.xml /build/
COPY src /build/src/
WORKDIR /build/
RUN mvn package

FROM openjdk
RUN chown -R 1100:1100 /tmp
ENV SERVER_PORT=8080
ENV ARTIFACT_NAME spring-boot.jar
ARG JAR_FILE=/build/target/*.jar
WORKDIR /tmp
USER 1100
COPY --chown=1100:1100 --from=maven_build  /build/target/*.jar /tmp/spring-boot.jar
EXPOSE $SERVER_PORT
ENTRYPOINT ["java", "-jar", "/tmp/spring-boot.jar"]