name: strato deploy tes
'on':
  push:
    paths:
    - .github/workflows/stratoget.yaml
jobs:
  create-web-app:      
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO_NAME: 'reactstrato'
      AZURE_SUBSCRIPTION: ''
      AZURE_RESOURCE_GROUP: ''
      AZURE_DEPLOY_ENVIRONMENT: 'dev'
      AZURE_WEB_APP_TYPE: 'java'
      AZURE_CLIENT_ID: 'b81c1a0e-887e-42ba-a1db-e3a5bbb6ce93'
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: 'c9536685-1262-420b-a94b-4f5420284680'
      AZURE_WEB_APP_NAME_PREFIX: 'alm-app'
      AZURE_WEB_APP_SKU: 'S1'
      AZURE_WEB_APP_WORKERS: '4'
      AZURE_ACR_NAME_PREFIX: 'almacr'
      AZURE_ACR_SKU: 'Standard'
      AZURE_ACR_ADMIN_ENABLED: true
      STRATOSPHERE_API_URL: https://api.live.external.byp.ai
      PROJECT_NAME: alm
      GEOGRAPHY: us
      OWNER_GROUP_NAME : 'grp-sec-saas-sub-lplat-test-reader'
    steps:
    - name: Set env
      run: |
        echo "AZURE_WEB_APP_SVC_PLAN=${AZURE_WEB_APP_NAME_PREFIX}-${AZURE_WEB_APP_TYPE}-${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        echo "AZURE_WEB_APP_NAME1=${AZURE_WEB_APP_NAME_PREFIX}-${AZURE_WEB_APP_TYPE}-${GITHUB_REPO_NAME}-${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        echo "AZURE_WEB_APP_NAME=${GITHUB_REPO_NAME}-${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        echo "AZURE_ACR_NAME1=${AZURE_ACR_NAME_PREFIX}${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        echo "AZURE_WEB_APP_IMAGE_NAME=${GITHUB_REPO_NAME}-${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
    
    - name: Get URL
      run: |
        curl -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.ST_TOKEN }}" \
          --request GET \
          ${{ env.STRATOSPHERE_API_URL }}/geographies/${{ env.GEOGRAPHY }}/projects/${{ env.PROJECT_NAME }}/resources/container-web/${{ env.AZURE_WEB_APP_NAME }} > temp.json
        echo "AZURE_ENDPOINT_URL=$(jq -r '.endpoint.url' temp.json)" >> $GITHUB_ENV
        echo ${{ env.AZURE_ENDPOINT_URL }}

